### ISSUE TITLE
Latex problem in quarto with modelsummary 2.5

### ISSUE THREAD

**Issue by morganwkelly** [vincentarelbundock/modelsummary#936]
This is a problem in both texlive on ubuntu and tinytex on windows so I am pretty sure that it is a general issue with modelsummary. It was not present in 2.2 but appeared when I upgraded to 2.5. 

Specifically, when rendering a table in pdf with modelsummary it generates the error "LaTeX Error: Environment tblr undefined." The full error message is at the end.

Here is a minimal reproducible example that can be pasted into an r code box in an empty quarto document. The default html format should be changed to pdf.

```{r}
library(modelsummary)
l1=lm(mpg~cyl,mtcars)
modelsummary(list(l1))
```

The full error message is below

ERROR: 
compilation failed- error
LaTeX Error: Environment tblr undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.221 \begin{tblr}
                  [         %% tabularray outer open

**Comment by vincentarelbundock** [comment]
Closing as duplicate. See solution here: https://github.com/vincentarelbundock/modelsummary/issues/931#issuecomment-3621186012
